version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy


builds:
  - env:
      - CGO_ENABLED=0
    binary: cred
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -mod=vendor

release:
  prerelease: auto

# universal_binaries:
#   - replace: true

checksum:
  name_template: "checksum.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
